name: real_time_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  signalr_flutter: ^0.2.0
  signalr_netcore: ^1.3.6
  signalr_core: ^1.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
